import type { TheaterLane } from "../domain/trade.js";

const lane = (input: Omit<TheaterLane, "disruption">): TheaterLane => ({
  ...input,
  disruption: 0,
});

export const globalTheaterLanes: Record<string, TheaterLane[]> = {
  "north-pacific": [
    lane({
      id: "japan-sea-lanes",
      routeId: "japan-sea-lanes",
      kind: "shipping",
      name: "Japan–Korea commercial lane",
      commodity: "industrial",
      countryIds: ["japan", "china", "soviet-union"],
      coordinates: [
        [35.1, 140.2],
        [35.8, 137.5],
        [37.8, 132.5],
      ],
      dailyValue: 28,
      dailyCapacity: 130,
      region: "north_pacific",
      coastal: true,
    }),
    lane({
      id: "yokosuka-guam-reinforcement",
      routeId: "yokosuka-guam-reinforcement",
      kind: "shipping",
      name: "Yokosuka–Guam reinforcement route",
      commodity: "military",
      countryIds: ["united-states", "japan"],
      coordinates: [
        [35.1, 140.2],
        [31, 147],
        [25, 150],
        [13.5, 144.7],
      ],
      dailyValue: 22,
      dailyCapacity: 80,
      region: "north_pacific",
      coastal: false,
    }),
    lane({
      id: "hokkaido-far-east-fishing",
      routeId: "hokkaido-far-east-fishing",
      kind: "shipping",
      name: "Hokkaido–Far East fishing grounds",
      commodity: "food",
      countryIds: ["japan", "soviet-union"],
      coordinates: [
        [42.5, 144.5],
        [44.5, 148],
        [46.5, 153],
      ],
      dailyValue: 9,
      dailyCapacity: 45,
      region: "north_pacific",
      coastal: true,
    }),
  ],
  "persian-gulf": [
    lane({
      id: "gulf-oil-route",
      routeId: "gulf-oil-route",
      kind: "shipping",
      name: "Kharg–Hormuz oil route",
      commodity: "fuel",
      countryIds: ["iraq", "iran", "united-states"],
      coordinates: [
        [29.2, 48.9],
        [27.5, 51.5],
        [26.5, 55.5],
      ],
      dailyValue: 42,
      dailyCapacity: 180,
      region: "persian_gulf",
      coastal: false,
    }),
    lane({
      id: "basra-kuwait-coastal-trade",
      routeId: "basra-kuwait-coastal-trade",
      kind: "shipping",
      name: "Basra–Kuwait coastal trade",
      commodity: "industrial",
      countryIds: ["iraq", "iran"],
      coordinates: [
        [30.5, 48.1],
        [29.8, 48.8],
        [29.3, 49.7],
      ],
      dailyValue: 16,
      dailyCapacity: 70,
      region: "persian_gulf",
      coastal: true,
    }),
    lane({
      id: "hormuz-air-corridor",
      routeId: "hormuz-air-corridor",
      kind: "air",
      name: "Gulf civilian air corridor",
      commodity: "passengers",
      countryIds: ["iran", "iraq", "united-states"],
      coordinates: [
        [25.3, 51.5],
        [26.2, 54],
        [26.6, 56.3],
      ],
      dailyValue: 8,
      dailyCapacity: 24,
      region: "persian_gulf",
      coastal: false,
    }),
  ],
  "indian-ocean": [
    lane({
      id: "arabian-sea-energy-route",
      routeId: "arabian-sea-energy-route",
      kind: "shipping",
      name: "Arabian Sea energy route",
      commodity: "fuel",
      countryIds: ["pakistan", "india", "australia"],
      coordinates: [
        [24, 66],
        [18, 70],
        [12, 75],
        [8, 80],
      ],
      dailyValue: 31,
      dailyCapacity: 140,
      region: "indian_ocean",
      coastal: false,
    }),
    lane({
      id: "mumbai-karachi-commerce",
      routeId: "mumbai-karachi-commerce",
      kind: "shipping",
      name: "Mumbai–Karachi commerce route",
      commodity: "industrial",
      countryIds: ["india", "pakistan"],
      coordinates: [
        [18.8, 70.5],
        [20, 67.5],
        [24.5, 66.5],
      ],
      dailyValue: 19,
      dailyCapacity: 85,
      region: "indian_ocean",
      coastal: true,
    }),
    lane({
      id: "diego-garcia-australia-route",
      routeId: "diego-garcia-australia-route",
      kind: "shipping",
      name: "Diego Garcia–Australia support route",
      commodity: "military",
      countryIds: ["united-states", "australia", "india"],
      coordinates: [
        [-7.3, 72.4],
        [-10, 85],
        [-18, 105],
        [-32, 115],
      ],
      dailyValue: 18,
      dailyCapacity: 65,
      region: "indian_ocean",
      coastal: false,
    }),
  ],
};
