import type { Contact } from "../domain/contacts.js";
import type { TrafficProfile } from "../domain/traffic.js";
import type { TheaterLane, TradeNode, TradeRoute } from "../domain/trade.js";

export const northernFlankTraffic: TrafficProfile[] = [
  {
    id: "norwegian-fishing",
    kind: "fishing",
    countryId: "norway",
    routeId: "coastal-fishing",
    baseDailyCount: 20,
    conflictSensitivity: 0.9,
    contactCategory: "fishing_vessel",
  },
  {
    id: "north-sea-merchants",
    kind: "merchant",
    countryId: "united-kingdom",
    routeId: "bergen-scapa-fuel",
    baseDailyCount: 8,
    conflictSensitivity: 0.55,
    contactCategory: "merchant_vessel",
  },
  {
    id: "nato-civil-air",
    kind: "civilian_air",
    countryId: "norway",
    routeId: "norwegian-air-corridor",
    baseDailyCount: 14,
    conflictSensitivity: 0.7,
    contactCategory: "civilian_aircraft",
  },
];

export const northernFlankTradeNodes: TradeNode[] = [
  {
    id: "bergen-fuel",
    countryId: "norway",
    name: "Bergen Fuel Terminal",
    commodity: "fuel",
    dailyCapacity: 100,
    dailyDemand: 0,
  },
  {
    id: "scapa-flow",
    countryId: "united-kingdom",
    name: "Scapa Flow",
    commodity: "fuel",
    dailyCapacity: 0,
    dailyDemand: 80,
  },
];

export const northernFlankTradeRoutes: TradeRoute[] = [
  {
    id: "bergen-scapa-fuel",
    originNodeId: "bergen-fuel",
    destinationNodeId: "scapa-flow",
    countryIds: ["norway", "united-kingdom"],
    capacity: 100,
    risk: 0.25,
    disruption: 0,
  },
];

export const northernFlankTheaterLanes: TheaterLane[] = [
  {
    id: "bergen-scapa-shipping-lane",
    routeId: "bergen-scapa-fuel",
    kind: "shipping",
    name: "Bergen–Scapa fuel lane",
    commodity: "fuel",
    countryIds: ["norway", "united-kingdom"],
    coordinates: [
      [60.39, 5.32],
      [59.75, 2.1],
      [58.96, -3.3],
    ],
    dailyValue: 18,
    dailyCapacity: 100,
    disruption: 0,
    region: "north_atlantic",
    coastal: true,
  },
  {
    id: "norwegian-air-corridor",
    routeId: "norwegian-air-corridor",
    kind: "air",
    name: "Norwegian civilian air corridor",
    commodity: "passengers",
    countryIds: ["norway", "united-kingdom"],
    coordinates: [
      [59.91, 10.75],
      [60.39, 5.32],
      [58.96, -3.3],
    ],
    dailyValue: 6,
    dailyCapacity: 14,
    disruption: 0,
    region: "north_atlantic",
    coastal: false,
  },
  {
    id: "oslo-bodo-coastal-commerce",
    routeId: "oslo-bodo-coastal-commerce",
    kind: "shipping",
    name: "Oslo–Bodø coastal commerce",
    commodity: "industrial",
    countryIds: ["norway"],
    coordinates: [
      [59.91, 10.75],
      [63.43, 10.4],
      [67.27, 14.36],
    ],
    dailyValue: 12,
    dailyCapacity: 45,
    disruption: 0,
    region: "north_atlantic",
    coastal: true,
  },
  {
    id: "tromso-lofoten-fishing",
    routeId: "tromso-lofoten-fishing",
    kind: "shipping",
    name: "Tromsø–Lofoten fishing grounds",
    commodity: "food",
    countryIds: ["norway"],
    coordinates: [
      [69.65, 18.96],
      [68.2, 14.55],
      [67.27, 14.36],
    ],
    dailyValue: 5,
    dailyCapacity: 30,
    disruption: 0,
    region: "north_atlantic",
    coastal: true,
  },
  {
    id: "aberdeen-bergen-cruise",
    routeId: "aberdeen-bergen-cruise",
    kind: "shipping",
    name: "Aberdeen–Bergen passenger route",
    commodity: "passengers",
    countryIds: ["united-kingdom", "norway"],
    coordinates: [
      [57.15, -2.1],
      [59.4, 1.5],
      [60.39, 5.32],
    ],
    dailyValue: 9,
    dailyCapacity: 24,
    disruption: 0,
    region: "north_atlantic",
    coastal: false,
  },
  {
    id: "atlantic-reinforcement-route",
    routeId: "atlantic-reinforcement-route",
    kind: "shipping",
    name: "North Atlantic reinforcement route",
    commodity: "military",
    countryIds: ["united-states", "united-kingdom", "norway"],
    coordinates: [
      [51.5, -20],
      [55, -12],
      [60, -10],
      [62, -4],
      [60.39, 5.32],
    ],
    dailyValue: 20,
    dailyCapacity: 80,
    disruption: 0,
    region: "north_atlantic",
    coastal: false,
  },
  {
    id: "oslo-tromso-air-corridor",
    routeId: "oslo-tromso-air-corridor",
    kind: "air",
    name: "Oslo–Tromsø domestic air corridor",
    commodity: "passengers",
    countryIds: ["norway"],
    coordinates: [
      [59.91, 10.75],
      [63.35, 10.35],
      [69.65, 18.96],
    ],
    dailyValue: 8,
    dailyCapacity: 20,
    disruption: 0,
    region: "north_atlantic",
    coastal: false,
  },
  {
    id: "continental-north-sea-freight",
    routeId: "continental-north-sea-freight",
    kind: "shipping",
    name: "Continental North Sea freight lane",
    commodity: "industrial",
    countryIds: ["netherlands", "germany", "denmark", "norway"],
    coordinates: [
      [51.95, 3.5],
      [53.7, 3.2],
      [55.5, 4.5],
      [57.7, 6.5],
      [60.39, 5.32],
    ],
    dailyValue: 24,
    dailyCapacity: 110,
    disruption: 0,
    region: "north_atlantic",
    coastal: false,
  },
  {
    id: "skagerrak-oslo-commerce",
    routeId: "skagerrak-oslo-commerce",
    kind: "shipping",
    name: "Skagerrak–Oslo commerce route",
    commodity: "industrial",
    countryIds: ["denmark", "germany", "norway"],
    coordinates: [
      [57.7, 8.8],
      [58.15, 9.25],
      [58.65, 9.65],
      [59.15, 10.05],
      [59.55, 10.5],
      [59.78, 10.65],
      [59.91, 10.75],
    ],
    dailyValue: 14,
    dailyCapacity: 65,
    disruption: 0,
    region: "north_atlantic",
    coastal: true,
  },
  {
    id: "north-sea-passenger-route",
    routeId: "north-sea-passenger-route",
    kind: "shipping",
    name: "Netherlands–Denmark passenger route",
    commodity: "passengers",
    countryIds: ["netherlands", "denmark", "germany"],
    coordinates: [
      [52.2, 3.6],
      [54.5, 5.5],
      [56.2, 7.5],
    ],
    dailyValue: 10,
    dailyCapacity: 28,
    disruption: 0,
    region: "north_atlantic",
    coastal: false,
  },
];

export const northernFlankContacts: Contact[] = [
  {
    id: "nf-fishing-01",
    domain: "surface",
    truthCategory: "fishing_vessel",
    truthIdentity: "Norwegian fishing vessel",
    truthDisposition: "neutral",
    assessment: {
      stage: "unknown",
      category: "unknown",
      confidence: 0,
      disposition: "unknown",
    },
    rulesOfEngagement: "identify_before_engage",
  },
  {
    id: "nf-merchant-01",
    domain: "surface",
    truthCategory: "merchant_vessel",
    truthIdentity: "Bergen-Scapa merchant convoy",
    truthDisposition: "friendly",
    assessment: {
      stage: "detected",
      category: "merchant_vessel",
      confidence: 0.55,
      disposition: "unknown",
    },
    rulesOfEngagement: "identify_before_engage",
  },
  {
    id: "nf-air-01",
    domain: "air",
    truthCategory: "civilian_aircraft",
    truthIdentity: "Norwegian civilian airliner",
    truthDisposition: "neutral",
    assessment: {
      stage: "categorized",
      category: "civilian_aircraft",
      confidence: 0.65,
      disposition: "unknown",
    },
    rulesOfEngagement: "identify_before_engage",
  },
];
